Created GameBadge component
siggame/ophelia pull request #56
Opened 2017-10-01 23:12 UTC by ColeDavis99

with four properties: opponentName, result, description, and gameID. The GameBadge component is also optimized for mobile viewing. I created a media query in main.css to account for the mobile styling. I also added visit_link.png to the client/src/images directory, but I am having trouble making the image actually appear on the website.

2017-10-06 07:38 UTC, renodubois requested changes
Left some initial comments, let me know what you think, and as always let me know if you have any questions!

By the way, let's get your backend ticket merged in before working on this too much, as that is a bit of a higher priority.

2017-10-06 07:38 UTC, renodubois commented on client/src/components/GameBadge.js
> +                  <img src="../images/visit_link.png" alt="visit_link.png" height="85vh" width="85vw"/>
If you feel comfortable doing it, try and put a SVG image here. They're very nice because they're drawn by the browser, and don't get pixel-ly at all. (you also don't have to worry about saving them anywhere, which is nice)

Do some Googling to try and figure out how to do it, but as always, if you run into issues let me know!

2017-10-06 07:38 UTC, renodubois commented on client/src/components/GameBadge.js
> +            <div style={{ backgroundColor:bgColor }} className="gamebadge-wrapper col-lg-12">
Go ahead and give the badges a fixed height. I think it'll make them look better overall. I'm not sure what the number for that should be exactly, but just eyeball it and see what looks good.

Let me know if you have any trouble with this, I'm being intentionally vague so you can make the call here on what looks good.

2017-10-06 07:38 UTC, renodubois commented on client/src/containers/main.css
> +.right img:hover{
Not a huge fan of how this looks now, but it might just be because of the image not actually being there. Once we get an image in there, we can see how that looks.

2017-10-16 02:43 UTC, ColeDavis99 commented on client/src/components/GameBadge.js
> +                  <img src="../images/visit_link.png" alt="visit_link.png" height="85vh" width="85vw"/>
I couldn't get an .svg file to work. I had trouble with a stubborn error when attempting to add .svg export functionality to GIMP. I then tried copy-pasting things from w3 schools and had no success.

2017-10-16 02:54 UTC, ColeDavis99 commented on client/src/components/GameBadge.js
> +            <div style={{ backgroundColor:bgColor }} className="gamebadge-wrapper col-lg-12">
I'm currently using bootstrap for the formatting of all the elements of the gamebadge component. The formatting as well as mobile-friendly functionality is lost whenever I attempt to stylize the elements manually with a fixed height.

2017-10-16 02:55 UTC, ColeDavis99 commented on client/src/containers/main.css
> +.right img:hover{
I've tested this with an image referenced with a URL, and I personally thought it looked pretty nice. I do agree though, the text looks like crap with an animated box shadow.

2017-10-22 23:08 UTC, renodubois commented on client/src/components/GameBadge.js
> +            <div style={{ backgroundColor:bgColor }} className="gamebadge-wrapper col-lg-12">
Ah, that's not ideal then. You might look into [this](https://tutorialzine.com/2015/05/simplify-your-stylesheets-with-the-magical-css-viewport-units) and see if you can implement that. There might also be a better solution for Bootstrap websites, so maybe do some Googling to see the best way to do that.

2017-10-22 23:52 UTC, renodubois requested changes
I know this is a lot, and if you don't feel comfortable going over this on your own (give it a try at least!) we can go over this at the meeting on Wednesday.

2017-10-22 23:52 UTC, renodubois commented on nbproject/project.properties
> +source.folder=
These look like files related to your IDE, so make sure you aren't committing these. You can add a rule in the `.gitignore` file to exclude these.

2017-10-22 23:52 UTC, renodubois commented on .gitignore
> +/nbproject/private/
Relating to my other comment, go ahead and just exclude the whole folder. I'd go ahead and follow the syntax of the other folder exclusions, so something like:
```
nbproject/
```

2017-10-22 23:52 UTC, renodubois commented on client/src/components/GameBadge.js
> +<!--  <img src="../images/visit_link.png" alt="visit_link.png" height="85vh" width="85vw"/>  -->
HTML Comments don't work inside of JSX, you'll need to do:
```
{/* your commented code here */}
```

2017-10-22 23:52 UTC, renodubois commented on client/src/components/GameBadge.js
> +              <div className="gamebadge-info left">
So, Bootstrap has a grid system that you can use, and will probably make more sense then using a custom CSS rule. Check it out [here](https://getbootstrap.com/docs/3.3/css/#grid) and let me know if you have any questions about implementing it.

2017-10-22 23:52 UTC, renodubois commented on client/src/components/GameBadge.js
> +                    style="fill:red;stroke:black;stroke-width:5;opacity:0.5" />
Style doesn't quite work like this in React. The `style` property takes an object, and you have your keys as the CSS Values.
For example, this style might look like:
```
style={{fill: 'red', stroke: 'black', ... }}
```
(note that the dots aren't part of the code, I just didn't want to write it all out)

This is something you'll run into a lot, so I want to make sure you're understanding how that works. React has a doc page on this, check it out and let me know if you have questions: https://reactjs.org/docs/dom-elements.html#style

2017-10-22 23:52 UTC, renodubois commented on client/src/components/GameBadge.js
> +                    <rect x="50" y="20" rx="20" ry="20" width="150" height="150"
So, SVG is a little confusing at first. Let's go over how this works at the meeting on Wednesday, and hopefully I can shed some more light on what this code is doing exactly.

2018-01-09 22:16 UTC, michael-beaver approved these changes
Now that the badges are made dynamically I think this looks good

2018-01-09 22:17 UTC, renodubois approved these changes

2018-01-09 22:17 UTC, merged